name: Publish to NPM with Webpack

on:
    push:
        branches: ['main']
    pull_request:
        branches: ['main']

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18.x

            - name: Install & Build
              run: |
                  npm install
                  npx webpack
                  npm run build

            - name: Log in to npm
              run: npm login --registry=https://registry.npmjs.org/ --scope=editorjs-indent-tune --always-auth=false
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            # - name: Publish to NPM
            #   run: npm publish --tag beta
            #   env:
            #       NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
